version: '3'

vars:
  # todo: update it to point to the remote dir if you plan to keep the proto to lua types gen.
  # PROTO_DIR: ./proto
  TS_GEN_DIR: gen/ts
  TYPES_OUTPUT: lua/neoweaver/types.lua
  SCRIPTS_DIR: scripts

tasks:
  types:proto:
    desc: Generate TypeScript types from mindweaver server protos
    dir: '{{.PROTO_DIR}}'
    preconditions:
      - sh: command -v buf
        msg: "buf is not installed. Install with: go install github.com/bufbuild/buf/cmd/buf@latest"
    cmds:
      - buf generate
    generates:
      - ../{{.TS_GEN_DIR}}/v3/*_pb.ts

  types:ts-to-lua:
    desc: Convert TypeScript types to Lua annotations
    deps:
      - types:proto
    preconditions:
      - sh: command -v bun
        msg: "bun is not installed. Install from: https://bun.sh"
    cmds:
      - bun run {{.SCRIPTS_DIR}}/ts-to-lua.ts {{.TS_GEN_DIR}} {{.TYPES_OUTPUT}}
    sources:
      - '{{.TS_GEN_DIR}}/v3/*_pb.ts'
    generates:
      - '{{.TYPES_OUTPUT}}'

  types:cleanup:
    desc: Remove temporary TypeScript files
    deps:
      - types:ts-to-lua
    cmds:
      - rm -rf {{.TS_GEN_DIR}}

  types:generate:
    desc: Generate Lua type annotations from protobuf definitions (full pipeline)
    aliases: [types:gen]
    deps:
      - types:proto
      - types:ts-to-lua
      - types:cleanup

  types:clean:
    desc: Remove all generated files (Lua types and TypeScript)
    cmds:
      - rm -f {{.TYPES_OUTPUT}}
      - rm -rf {{.TS_GEN_DIR}}

  deps:
    desc: Download dependencies for testing and documents gen
    cmds:
      - mkdir -p deps
      - task: deps:mini
      - task: deps:panvimdoc

  deps:mini:
    desc: Download mini.test and mini.doc dependencies in the deps directory
    dir: deps
    cmds:
      - git clone --filter=blob:none https://github.com/echasnovski/mini.nvim
    status:
      - test -d mini.nvim/.git

  deps:panvimdoc:
    desc: Download panvimdoc for generating documentation
    dir: deps
    cmds:
      - git clone --filter=blob:none https://github.com/kdheepak/panvimdoc
    status:
      - test -d panvimdoc/.git

  docs:gen:
    desc: Generate nvim help file documentation
    deps: ['deps']

  docs:gen:panvimdoc:
    desc: Generate vimdoc from markdown using panvimdoc
    deps: ['deps:panvimdoc']
    cmds:
      - >
        pandoc
        --shift-heading-level-by=0
        --metadata=project:neoweaver
        --metadata=vimversion:"Neovim 0.11+"
        --metadata=toc:true
        --metadata=description:"Neoweaver - Neovim client for MindWeaver"
        --metadata=treesitter:true
        --metadata=incrementheadinglevelby:0
        --metadata=dedupsubheadings:true
        --metadata=ignorerawblocks:false
        --metadata=docmapping:false
        --metadata=docmappingprojectname:true
        --metadata=demojify:false
        --lua-filter=deps/panvimdoc/scripts/include-files.lua
        --lua-filter=deps/panvimdoc/scripts/skip-blocks.lua
        --lua-filter=scripts/pandoc.lua
        -t deps/panvimdoc/scripts/panvimdoc.lua
        docs/vimdoc.md
        -o doc/neoweaver.txt
    sources:
      - docs/vimdoc.md
      - docs/installation.md
      - docs/configuration.md
      - docs/commands.md
      - docs/keymaps.md
      - scripts/pandoc.lua
    generates:
      - doc/neoweaver.txt

  docs:api:
    desc: Generate API documentation from LuaLS annotations using mini.doc
    deps: ['deps:mini']
    cmds:
      - nvim --headless --noplugin -u scripts/minimal_init_docs.lua -c "quit"
    sources:
      - lua/neoweaver/init.lua
      - lua/neoweaver/types.lua
    generates:
      - doc/neoweaver_api.txt

  docs:tags:
    desc: Generate vim help tags
    deps: [docs:api]
    cmds:
      - nvim --headless -c 'helptags doc' -c 'quit'
    sources:
      - doc/*.txt
    generates:
      - doc/tags

