version: '3'

vars:
  SCRIPTS_DIR: scripts

tasks:
  deps:mini:
    desc: Download mini.nvim for API documentation generation
    dir: deps
    cmds:
      - git clone --filter=blob:none https://github.com/echasnovski/mini.nvim
    status:
      - test -d mini.nvim/.git

  deps:panvimdoc:
    desc: Download panvimdoc for vimdoc generation
    dir: deps
    cmds:
      - git clone --filter=blob:none https://github.com/kdheepak/panvimdoc
    status:
      - test -d panvimdoc/.git

  docs:gen:panvimdoc:
    desc: Generate vimdoc from markdown using panvimdoc
    deps: ['deps:panvimdoc']
    cmds:
      - >
        pandoc
        --shift-heading-level-by=0
        --metadata=project:neoweaver
        --metadata=vimversion:"Neovim 0.11+"
        --metadata=toc:true
        --metadata=description:"Neoweaver - Neovim client for MindWeaver"
        --metadata=treesitter:true
        --metadata=incrementheadinglevelby:0
        --metadata=dedupsubheadings:true
        --metadata=ignorerawblocks:false
        --metadata=docmapping:false
        --metadata=docmappingprojectname:true
        --metadata=demojify:false
        --lua-filter=deps/panvimdoc/scripts/include-files.lua
        --lua-filter=deps/panvimdoc/scripts/skip-blocks.lua
        --lua-filter=scripts/pandoc.lua
        -t deps/panvimdoc/scripts/panvimdoc.lua
        docs/vimdoc.md
        -o doc/neoweaver.txt
    sources:
      - docs/vimdoc.md
      - docs/installation.md
      - docs/configuration.md
      - docs/commands.md
      - docs/keymaps.md
      - scripts/pandoc.lua
    generates:
      - doc/neoweaver.txt

  docs:api:
    desc: Generate API documentation from LuaLS annotations using mini.doc
    deps: ['deps:mini']
    cmds:
      - nvim --headless --noplugin -u scripts/minimal_init_docs.lua -c "quit"
    sources:
      - lua/neoweaver/init.lua
      - lua/neoweaver/types.lua
    generates:
      - doc/neoweaver_api.txt

  docs:tags:
    desc: Generate vim help tags
    deps: ['docs:api']
    cmds:
      - nvim --headless -c 'helptags doc' -c 'quit'
    sources:
      - doc/*.txt
    generates:
      - doc/tags
